GET https://wipfogyruipbdpacueap.supabase.co/rest/v1/products?select=name
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcGZvZ3lydWlwYmRwYWN1ZWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzM2NTEyNTAsImV4cCI6MTk4OTIyNzI1MH0.y6tBJ2M_zvhkTtFHF1Abtsz2Hapw4LaWbG6nS5x4s-0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcGZvZ3lydWlwYmRwYWN1ZWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzM2NTEyNTAsImV4cCI6MTk4OTIyNzI1MH0.y6tBJ2M_zvhkTtFHF1Abtsz2Hapw4LaWbG6nS5x4s-0

###

POST https://wipfogyruipbdpacueap.supabase.co/rest/v1/products
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcGZvZ3lydWlwYmRwYWN1ZWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzM2NTEyNTAsImV4cCI6MTk4OTIyNzI1MH0.y6tBJ2M_zvhkTtFHF1Abtsz2Hapw4LaWbG6nS5x4s-0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjczNjYxMDA4LCJzdWIiOiJhZDM2MWZiNC1jZGNhLTQ3M2EtYTQzYi03MjliNDYzZjk3ZmUiLCJlbWFpbCI6ImRldnJ6enRAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib3RwIiwidGltZXN0YW1wIjoxNjczNjU3NDA4fV0sInNlc3Npb25faWQiOiI0M2VhNmE0Yy1iYTcwLTRlZDYtODg1OS03MTk5NzVhYTEyOWUifQ.kVuA4GVA_OzhHOCoYooYcD8AJn2GJDtzblWijvOMpAc
Content-Type: application/json

{
    "name": "name7"
}

###

PATCH https://wipfogyruipbdpacueap.supabase.co/rest/v1/products?id=eq.6
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcGZvZ3lydWlwYmRwYWN1ZWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzM2NTEyNTAsImV4cCI6MTk4OTIyNzI1MH0.y6tBJ2M_zvhkTtFHF1Abtsz2Hapw4LaWbG6nS5x4s-0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjczNjYxMDA4LCJzdWIiOiJhZDM2MWZiNC1jZGNhLTQ3M2EtYTQzYi03MjliNDYzZjk3ZmUiLCJlbWFpbCI6ImRldnJ6enRAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib3RwIiwidGltZXN0YW1wIjoxNjczNjU3NDA4fV0sInNlc3Npb25faWQiOiI0M2VhNmE0Yy1iYTcwLTRlZDYtODg1OS03MTk5NzVhYTEyOWUifQ.kVuA4GVA_OzhHOCoYooYcD8AJn2GJDtzblWijvOMpAc
Content-Type: application/json

{
    "name": "name88"
}

###

DELETE https://wipfogyruipbdpacueap.supabase.co/rest/v1/products?id=eq.3
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcGZvZ3lydWlwYmRwYWN1ZWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzM2NTEyNTAsImV4cCI6MTk4OTIyNzI1MH0.y6tBJ2M_zvhkTtFHF1Abtsz2Hapw4LaWbG6nS5x4s-0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjczNjYxMDA4LCJzdWIiOiJhZDM2MWZiNC1jZGNhLTQ3M2EtYTQzYi03MjliNDYzZjk3ZmUiLCJlbWFpbCI6ImRldnJ6enRAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib3RwIiwidGltZXN0YW1wIjoxNjczNjU3NDA4fV0sInNlc3Npb25faWQiOiI0M2VhNmE0Yy1iYTcwLTRlZDYtODg1OS03MTk5NzVhYTEyOWUifQ.kVuA4GVA_OzhHOCoYooYcD8AJn2GJDtzblWijvOMpAc